services:
  backend:
    build: ./backend
    container_name: estimate-backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: estimate-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host"]

  db:
    image: mysql:8.0
    container_name: estimate-db
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: estimate_db
      MYSQL_USER: estimate_user
      MYSQL_PASSWORD: estimate_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"

volumes:
  mysql_data:
    driver: local
  media_volume:
    driver: local
